[icons]
name = "awesome5"
[icons.overrides]
disk_drive = "ï—½ "
backlight_empty = "ğŸŒ‘"
backlight_full = "ğŸŒ•"
backlight_partial1 = "ğŸŒ’"
backlight_partial3 = "ğŸŒ”"
net_down = "ğŸ ‡"
memory_mem = "î§“"
time = "â³"

[theme]
name = "gruvbox-dark"
[theme.overrides]
separator = ""

[[block]]
block = "custom"
command = "gmail"
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GiB"
interval = 60
warning = 15.0
alert = 10.0
format = "{icon}{alias}{available}({percentage}){unit}"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}% {frequency}GHz"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}GB"
format_swap = "{SUm}MB"
icons = true
clickable = true
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "sound"
driver = "pulseaudio"
show_volume_when_muted = true

[[block]]
block = "backlight"
step_width = 5

[[block]]
block = "net"
device = "enp0s31f6"
format = "{speed_down}"
interval = 5
speed_min_unit = "M"
use_bits = false
hide_missing = true
hide_inactive = true

[[block]]
block = "net"
device = "wlan0"
format = "{ssid}{speed_down}"
interval = 5
speed_min_unit = "M"
use_bits = false
hide_missing = true
hide_inactive = true

[[block]]
block = "keyboard_layout"
driver = "sway"
sway_kb_identifier = "1:1:AT_Translated_Set_2_keyboard"
format = "{layout}"

[[block]]
block = "time"
interval = 15
format = "%d.%m %R"
on_click = "swaymsg -q exec 'gsimplecal'"
