[icons]
name = "awesome5"
[icons.overrides]
backlight_empty = "ğŸŒ‘"
backlight_full = "ğŸŒ•"
backlight_partial1 = "ğŸŒ’"
backlight_partial3 = "ğŸŒ”"
bat_charging = " ï–‡ "
bat_discharging = " ï–‚ "
bat_empty = " ï•¹"
bat_full = " ï•¸ "
bat_half = " ï•½ "
bat_quarter = " ï•» "
bat_three_quarters = " ï•¿ "
cpu = "ï‹›"
disk_drive = "ïš· "
memory_mem = "î‰€ "
net_down = "â‡Š"
time = "â³"
volume_muted = "ï‘¦ "

[theme]
name = "gruvbox-dark"
[theme.overrides]
separator = ""

[[block]]
block = "custom"
command = "gmail"
interval = 60

[[block]]
block = "disk_space"
alert = 10.0
alert_absolute = true
alias = "/"
format = "{icon}{alias}{free}{unit}"
info_type = "free"
interval = 300
path = "/"
unit = "GB"
warning = 15.0

[[block]]
block = "cpu"
format = "{barchart} {utilization} {frequency}"
interval = 10

[[block]]
block = "memory"
clickable = true
critical_mem = 95
critical_swap = 95
display_type = "memory"
format_mem = "{Mug}GB"
format_swap = "{SUm}MB"
icons = true
interval = 60
warning_mem = 80
warning_swap = 80

[[block]]
#device = "BAT1"
device = "DisplayDevice"
block = "battery"
driver = "upower"
format = "{percentage}% {time}"
#interval = 60

[[block]]
block = "sound"
driver = "auto"
show_volume_when_muted = true

[[block]]
block = "backlight"
step_width = 5

[[block]]
block = "net"
device = "enp0"
format = "{speed_down}"
hide_inactive = true
hide_missing = true
interval = 5
speed_min_unit = "M"
use_bits = false

[[block]]
block = "net"
device = "wlan0"
format = "{signal_strength} {ssid}{speed_down}"
hide_inactive = true
hide_missing = true
interval = 5
speed_min_unit = "M"
use_bits = false

[[block]]
block = "keyboard_layout"
driver = "sway"
format = "{layout}"
sway_kb_identifier = "1:1:AT_Translated_Set_2_keyboard"
[block.mappings]
"English (US)" = "EN"
"Ukrainian (N/A)" = "UK"

[[block]]
block = "bluetooth"
mac = ""
label = "B"
hide_disconnected = false

[[block]]
block = "time"
format = "%d.%m %R"
interval = 45
on_click = "swaymsg -q exec 'gsimplecal'"
