[icons]
name = "awesome5"
[icons.overrides]
backlight_empty = "ğŸŒ‘"
backlight_full = "ğŸŒ•"
backlight_partial1 = "ğŸŒ’"
backlight_partial3 = "ğŸŒ”"
cpu = "ï‹›"
disk_drive = "ï · "
memory_mem = "î‰€ "
net_down = "â‡Š"
time = "â³"

[theme]
name = "gruvbox-dark"
[theme.overrides]
separator = ""

[[block]]
block = "custom"
command = "gmail"
interval = 5

[[block]]
block = "disk_space"
alert = 10.0
alias = "/"
format = "{icon}{alias}{available}({percentage}){unit}"
info_type = "available"
interval = 60
path = "/"
unit = "GiB"
warning = 15.0

[[block]]
block = "cpu"
format = "{barchart} {utilization}% {frequency}GHz"
interval = 1

[[block]]
block = "memory"
clickable = true
critical_mem = 95
critical_swap = 95
display_type = "memory"
format_mem = "{Mug}GB"
format_swap = "{SUm}MB"
icons = true
warning_mem = 80
warning_swap = 80

[[block]]
block = "battery"
format = "{percentage}% {time}"
interval = 10

[[block]]
block = "sound"
driver = "pulseaudio"
show_volume_when_muted = true

[[block]]
block = "backlight"
step_width = 5

[[block]]
block = "net"
device = "enp0"
format = "{speed_down}"
hide_inactive = true
hide_missing = true
interval = 5
speed_min_unit = "M"
use_bits = false

[[block]]
block = "net"
device = "wlan0"
format = "{ssid}{speed_down}"
hide_inactive = true
hide_missing = true
interval = 5
speed_min_unit = "M"
use_bits = false

[[block]]
block = "keyboard_layout"
driver = "sway"
format = "{layout}"
sway_kb_identifier = "1:1:AT_Translated_Set_2_keyboard"

[[block]]
block = "time"
format = "%d.%m %R"
interval = 15
on_click = "swaymsg -q exec 'gsimplecal'"
